server:
  port: 8999
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///roadmap_data
  redis:
    port: 6379
    host: localhost
logging:
  level:
    com.roam: debug

